on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v1.2
      with:
        host:  ${{ secrets.FTP_SERVER }}
        port: 22
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: '/web/'
        remoteDir: '/var/www/app/'
        excludeMode: 'remove'
